#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use yii\console\Application;

require __DIR__ . '/../bootstrap.php';

$config = require __DIR__ . '/config/console.php';

$application = new Application($config);
$exitCode = $application->run();
exit($exitCode);
